<!DOCTYPE html>
<html lang="en">

<head>
  <title>Bazaar Ceramics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="css/style.css" type="text/css">
  <link rel="stylesheet" href="css/laptop.css" type="text/css">
  <link rel="stylesheet" href="css/tablet.css" type="text/css">
  <link rel="stylesheet" href="css/mobile.css" type="text/css">
  <link rel="stylesheet" href="css/layout.css" type="text/css">
  <script src="scripts/java.js"></script>