<!DOCTYPE html>
<html lang="en">

<head>
  <title>Bazaar Ceramics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="../css/style.css" rel="stylesheet" type="text/css">
  <link href="../css/laptop.css" rel="stylesheet" type="text/css">
  <link href="../css/tablet.css" rel="stylesheet" type="text/css">
  <link href="../css/mobile.css" rel="stylesheet" type="text/css">
  <link href="../css/layout.css" rel="stylesheet" type="text/css">
  <script src="../scripts/java.js"></script>